### ISSUE TITLE
Exception thrown on entering minecart

### ISSUE THREAD

**Issue by PhasecoreX** [quat1024/AutoThirdPerson#7]
When I right click a minecart, this is thrown and my game crashes:
```
[Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_11145
	at agency.highlysuspect.autothirdperson.AutoThirdPerson.mountOrDismount(AutoThirdPerson.java:99) ~[auto_third_person-fabric-1.19.2-1.2.1.jar:?]
	at net.minecraft.class_746.handler$zej000$onStartRiding(class_746.java:1813) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5873(class_746.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11080(class_634.java:968) ~[client-intermediary.jar:?]
	at net.minecraft.class_2752.method_11842(class_2752.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2752.method_11054(class_2752.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1144) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```
Using Prism Launcher, 1.19.3, Fabulously Optimized modpack version 4.6.0-beta.3

I saw on the main page "1.19.3: No plans, all the mods are on 1.19.2". Wasn't sure if that meant you have no interest in 1.19.3 at all, or just that no one had run into issues yet/you were waiting for more mods to support 1.19.3.

**Comment by quat1024** [comment]
It doesn't work on 1.19.3

**Comment by quat1024** [comment]
Closing because 1.19.3 will not be a supported version and i'm workin on a .4 one.
